# -*- coding: utf-8 -*-
"""salarypred

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1azhEuTfrCEnIwmXQnb68Ik_7zMoHdSdK
"""

import pandas as pd

df = pd.read_csv("/content/Salary_Dataset_DataScienceLovers.csv")
df

df.head()

df.isnull().sum()

for column in df.columns:
  if df[column].dtype == "object":
    df[column] = df[column].fillna(df[column].mode()[0])
  else:
    df[column] = df[column].fillna(df[column].mean())
  print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
X = df.drop('Salary', axis=1)
y = df['Salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained successfully!")

# The data has already been split into training and testing sets in a previous step.
# X_train, X_test, y_train, y_test are already available.

from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

def train_evaluate_model(model, X_train, y_train, X_test, y_test, model_name):
    print(f"\n--- {model_name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"Root Mean Squared Error: {rmse:.2f}")
    print(f"R-squared: {r2:.2f}")

train_evaluate_model(KNeighborsRegressor(n_neighbors=5), X_train, y_train, X_test, y_test, "K-Nearest Neighbors Regressor")

train_evaluate_model(DecisionTreeRegressor(random_state=42), X_train, y_train, X_test, y_test, "Decision Tree Regressor")
train_evaluate_model(RandomForestRegressor(random_state=42), X_train, y_train, X_test, y_test, "Random Forest Regressor")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure X_train, y_train, X_test, y_test, and 'model' (LinearRegression) are available from previous cells
# If model was not explicitly named in the LinearRegression cell, we define it here for comparison:

# 1. Evaluate Linear Regression model (already trained as 'model')
print("\n--- Linear Regression ---")
y_pred_lr = model.predict(X_test)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)
print(f"Mean Squared Error: {mse_lr:.2f}")
print(f"Root Mean Squared Error: {rmse_lr:.2f}")
print(f"R-squared: {r2_lr:.2f}")

# Define models and collect results into a dictionary for easier comparison
models = {
    "Linear Regression": {
        "model": model,
        "mse": mse_lr,
        "rmse": rmse_lr,
        "r2": r2_lr
    },
    "K-Nearest Neighbors Regressor": {
        "model": KNeighborsRegressor(n_neighbors=5),
        "mse": 620584848289.41,
        "rmse": 787772.08,
        "r2": -0.53
    },
    "Decision Tree Regressor": {
        "model": DecisionTreeRegressor(random_state=42),
        "mse": 2484415021401.04,
        "rmse": 1576202.72,
        "r2": -5.13
    },
    "Random Forest Regressor": {
        "model": RandomForestRegressor(random_state=42),
        "mse": 623993827858.30,
        "rmse": 789932.80,
        "r2": -0.54
    }
}

# Create a DataFrame for comparison
results_df = pd.DataFrame({
    'Model': [name for name in models.keys()],
    'MSE': [data['mse'] for data in models.values()],
    'RMSE': [data['rmse'] for data in models.values()],
    'R-squared': [data['r2'] for data in models.values()]
})

print("\n--- Model Comparison ---")
print(results_df)

# Create comparison graphs
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle('Model Performance Comparison', fontsize=16)

# MSE Plot
sns.barplot(ax=axes[0], x='Model', y='MSE', data=results_df)
axes[0].set_title('Mean Squared Error')
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=45, ha='right')

# RMSE Plot
sns.barplot(ax=axes[1], x='Model', y='RMSE', data=results_df)
axes[1].set_title('Root Mean Squared Error')
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45, ha='right')

# R-squared Plot
sns.barplot(ax=axes[2], x='Model', y='R-squared', data=results_df)
axes[2].set_title('R-squared')
axes[2].set_xticklabels(axes[2].get_xticklabels(), rotation=45, ha='right')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

best_model_row = results_df.loc[results_df['R-squared'].idxmax()]
best_model_name = best_model_row['Model']


if best_model_name == "Linear Regression":

    best_trained_model = model
elif best_model_name == "K-Nearest Neighbors Regressor":
    knn_model = KNeighborsRegressor(n_neighbors=5)
    knn_model.fit(X_train, y_train)
    best_trained_model = knn_model
elif best_model_name == "Decision Tree Regressor":
    dt_model = DecisionTreeRegressor(random_state=42)
    dt_model.fit(X_train, y_train)
    best_trained_model = dt_model
elif best_model_name == "Random Forest Regressor":
    rf_model = RandomForestRegressor(random_state=42)
    rf_model.fit(X_train, y_train)
    best_trained_model = rf_model
else:
    print(f"Warning: Could not find the trained model for {best_model_name}.")
    best_trained_model = None

if best_trained_model is not None:

    filename = 'best_model.pkl'
    with open(filename, 'wb') as file:
        pickle.dump(best_trained_model, file)
    print(f"The best performing model ({best_model_name}) has been saved to {filename}")


    from google.colab import files
    files.download(filename)
else:
    print("No model was saved due to an issue retrieving the best trained model.")

